name: Enqueue API CI
on: [push, pull_request]

jobs:
  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install libsodium
        run: sudo apt install libsodium-dev

      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@3.2
        with:
          cli: 1.10.3.822

      - name: Run tests
        run: clojure -X:test
