name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@5.1
        with:
          cli: '1.11.1.1107'

      - name: Run clj-kondo
        run: do/test/lint

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install libsodium
        run: sudo apt install libsodium-dev

      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@5.1
        with:
          cli: '1.11.1.1107'

      - name: Run tests
        run: do/test/unit

  integration-test:
    name: Integration test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install libsodium
        run: sudo apt install libsodium-dev

      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@5.1
        with:
          cli: '1.11.1.1107'

      - name: Run tests
        run: do/test/integration

  system-test:
    name: System test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install libsodium
        run: sudo apt install libsodium-dev

      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@5.1
        with:
          cli: '1.11.1.1107'

      - name: Run tests
        run: do/test/system
