name: CI
on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup clj-kondo
        uses: DeLaGuardo/setup-clj-kondo@afc83dbbf4e7e32e04649e29dbf30668d30e9e3e
        with:
          version: '2022.03.09'

      - name: Run clj-kondo
        run: clj-kondo --lint src

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install libsodium
        run: sudo apt install libsodium-dev

      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@4.0
        with:
          cli: '1.10.3.1093'

      - name: Run tests
        run: clojure -X:test :types '[:unit]'

  component-test:
    name: Component test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install libsodium
        run: sudo apt install libsodium-dev

      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@4.0
        with:
          cli: '1.10.3.1093'

      - name: Run tests
        run: |
          do/database/test/start
          clojure -X:test :types '[:component]'
          docker stop enqueue-db-test

  system-test:
    name: System test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install libsodium
        run: sudo apt install libsodium-dev

      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@4.0
        with:
          cli: '1.10.3.1093'

      - name: Run tests
        run: |
          do/database/test/start
          clojure -X:test :types '[:system]'
          docker stop enqueue-db-test
